# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MvgcConsole < Formula
  desc "Axemere AI Gateway console — local web dashboard"
  homepage "https://axemere.ai"
  version "1.0.5"
  license "Proprietary"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/Axemere-LLC/mvgc-releases/releases/download/v1.0.5/mvgc-console_1.0.5_darwin_arm64.tar.gz"
    sha256 "5ed7867f783f612940b7a3247e48e9b3a67e32d919602bce7d2bec21f00fbebc"

    define_method(:install) do
      bin.install "mvgc-console"
      (var/"log/mvgc").mkpath
    end
  end

  depends_on arch: :arm64

  def caveats
    <<~EOS
      To start the console, set your gateway URL and run:
        CONSOLE_GATEWAY_URL=http://localhost:7080 mvgc-console

      The dashboard is available at http://localhost:7091

      To set a password for the console UI:
        CONSOLE_GATEWAY_URL=http://localhost:7080 CONSOLE_PASSWORD=secret mvgc-console

      Logs are written to stdout. To run as a service:
        brew services start mvgc-console
    EOS
  end

  service do
    run [opt_bin/"mvgc-console"]
    keep_alive true
    log_path var/"log/mvgc/console.log"
    error_log_path var/"log/mvgc/console-error.log"
    environment_variables CONSOLE_GATEWAY_URL: "http://localhost:7080",
                          CONSOLE_LISTEN_ADDR: ":7091"
  end

  test do
    assert_match "mvgc-console", shell_output("#{bin}/mvgc-console --help 2>&1")
  end
end
