# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MvgcGateway < Formula
  desc "Axemere AI Gateway — self-hosted AI API governance gateway"
  homepage "https://axemere.ai"
  version "1.0.0-rc5"
  license "Proprietary"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/Axemere-LLC/mvgc-releases/releases/download/v1.0.0-rc5/mvgc-gateway_1.0.0-rc5_darwin_arm64.tar.gz"
    sha256 "9838b701e66a1508b8a7e917800654b6c43741421baf03196880d8d56ceba5ad"

    define_method(:install) do
      bin.install "mvgc-gateway"
      bin.install "mvgc"
      (etc/"mvgc").mkpath
      (etc/"mvgc/mvgc.yaml.default").atomic_write(File.read("mvgc.yaml"))
      (etc/"mvgc/mvgc.yaml").write(File.read("mvgc.yaml")) unless (etc/"mvgc/mvgc.yaml").exist?
      (var/"mvgc/configs/policies").mkpath
      bundle_dest = var/"mvgc/configs/policies/bundle.yaml"
      bundle_dest.write(File.read("configs/policies/bundle.yaml")) unless bundle_dest.exist?
      (var/"mvgc/configs/policies/available").mkpath
      Dir["configs/policies/available/*.yaml"].each do |f|
        dest = var/"mvgc/configs/policies/available"/File.basename(f)
        dest.write(File.read(f)) unless dest.exist?
      end
      (var/"mvgc/configs/policies/addons").mkpath
      # Create default symlinks for all add-ons except claude-cli-proxy (user opts in).
      %w[provider-openai provider-anthropic provider-gemini
         provider-azure-openai provider-cohere deny-unknown-host].each do |name|
        link = var/"mvgc/configs/policies/addons/#{name}.yaml"
        target = var/"mvgc/configs/policies/available/#{name}.yaml"
        link.make_symlink(target) unless link.exist?
      end
      (var/"mvgc/configs/credentials").mkpath
      Dir["configs/credentials/*.yaml"].each do |f|
        dest = var/"mvgc/configs/credentials"/File.basename(f)
        dest.write(File.read(f)) unless dest.exist?
      end
      (var/"mvgc/configs/workloads").mkpath
      Dir["configs/workloads/*.yaml"].each do |f|
        dest = var/"mvgc/configs/workloads"/File.basename(f)
        dest.write(File.read(f)) unless dest.exist?
      end
      (var/"mvgc/configs/examples").mkpath
      Dir["configs/examples/*.yaml"].each do |f|
        dest = var/"mvgc/configs/examples"/File.basename(f)
        dest.write(File.read(f)) unless dest.exist?
      end
      (var/"mvgc/configs/examples/README.md").write(File.read("configs/examples/README.md")) unless (var/"mvgc/configs/examples/README.md").exist?
      (var/"log/mvgc").mkpath
    end
  end

  depends_on arch: :arm64

  def caveats
    <<~EOS
      Configuration file installed at:
        #{etc}/mvgc/mvgc.yaml

      Default policy files installed at:
        #{var}/mvgc/configs/policies/

      Example and starting-point configs installed at:
        #{var}/mvgc/configs/examples/
      See #{var}/mvgc/configs/examples/README.md for usage instructions.

      Credential seed file installed at:
        #{var}/mvgc/configs/credentials/credentials.yaml

      Workload seed file installed at:
        #{var}/mvgc/configs/workloads/workloads.yaml

      Edit the config file to set your DATABASE_URL, MVGC_ADMIN_TOKEN, and
      connector credentials before starting the service.

      To start mvgc-gateway now and restart at login:
        brew services start mvgc-gateway

      Logs are written to:
        #{var}/log/mvgc/gateway.log
        #{var}/log/mvgc/gateway-error.log
    EOS
  end

  service do
    run [opt_bin/"mvgc-gateway"]
    keep_alive true
    working_dir var/"mvgc"
    log_path var/"log/mvgc/gateway.log"
    error_log_path var/"log/mvgc/gateway-error.log"
    environment_variables MVGC_CONFIG: etc/"mvgc/mvgc.yaml",
                          MVGC_CREDENTIALS_DIR: var/"mvgc/configs/credentials",
                          MVGC_WORKLOADS_DIR: var/"mvgc/configs/workloads"
  end

  test do
    assert_match "mvgc-gateway", shell_output("#{bin}/mvgc-gateway --version")
    assert_match "mvgc", shell_output("#{bin}/mvgc version")
  end
end
