# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MvgcConsole < Formula
  desc "Axemere AI Gateway console — local web dashboard"
  homepage "https://axemere.ai"
  version "1.1.5"
  license "Proprietary"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/Axemere-LLC/mvgc-releases/releases/download/v1.1.5/mvgc-console_1.1.5_darwin_arm64.tar.gz"
    sha256 "0e6fc892e8a1e7986e69251967e384090d6b0a8c9d007dde93c76ba3670686c1"

    define_method(:install) do
      bin.install "mvgc-console"
      (var/"log/mvgc").mkpath
    end
  end

  depends_on arch: :arm64

  def caveats
    <<~EOS
      To start the console, set your gateway URL and run:
        CONSOLE_GATEWAY_URL=http://localhost:7080 mvgc-console

      The dashboard is available at http://localhost:7091

      To set a password for the console UI:
        CONSOLE_GATEWAY_URL=http://localhost:7080 CONSOLE_PASSWORD=secret mvgc-console

      Logs are written to stdout. To run as a service:
        brew services start mvgc-console
    EOS
  end

  service do
    run [opt_bin/"mvgc-console"]
    keep_alive true
    log_path var/"log/mvgc/console.log"
    error_log_path var/"log/mvgc/console-error.log"
    environment_variables CONSOLE_GATEWAY_URL: "http://localhost:7080",
                          CONSOLE_LISTEN_ADDR: ":7091"
  end

  test do
    assert_match "mvgc-console", shell_output("#{bin}/mvgc-console --help 2>&1")
  end
end
